title: RohanDG Theme
description: A simple Jekyll theme for personal blogs and portfolios.
author: Rohan de Graaf
email: rohan@rohandg.com
url: https://rohandg.com/
baseurl: ""
theme: rohandg-theme
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      layout: default