title: RohanDG Theme
description: A simple Jekyll theme for personal blogs and portfolios.
author: Your Name
email: your.email@example.com
url: https://yourwebsite.com
baseurl: ""
theme: rohandg-theme
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      layout: default